### ISSUE TITLE
End Suite is Failing with Finish Launch Not allowed

### ISSUE THREAD

**Issue by samratashok87** [ailjushkin/robotframework-reportportal-ng#6]
Hi, 

While using the listener when the test ends the Finish Launch is failing from the test.
Hence the Launch is continuing to run. The error seen is like 

Finish launch is not allowed. Launch '5aa66881bfe5230001939fea' has items '[5aa66881bfe5230001939fec]' with 'IN_PROGRESS' status

We are facing this issue whenever we tried to run with the listener. Please help.

**Comment by ailjushkin** [comment]
Hi. Seems like there is a place where listener fails to close a test section. To find that test, please do not force finish your launch. Wait for the error and after it please open your launch in Report Portal and find a test which is not ended. You should debug listener with python debugger with this single test.

Please examine error logs to get more detailed information about the failure. This will help to fix the listener.

**Comment by samratashok87** [comment]
Thank you will do as suggested and update.

**Comment by ailjushkin** [comment]
@samratashok87 output.xml or debugfile: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#debug-file

**Comment by ailjushkin** [comment]
@samratashok87 hi, please, check with new version and, if the error does not reproduces, please close your issue.

`pip install -U robotframework_reportportal_ng`

**Comment by amalsgit** [comment]
Hi @ailjushkin, I am also facing the same error. I tried today with the latest version of robotframework_reportportal_ng (1.0.4.7).
This is the command used for execution: 
`python -m robot -d results --listener reportportal_listener --escape quot:Q --variable RP_ENDPOINT:http://192.168.99.100:8080 --variable RP_UUID:531345ef-2c3a-4b28-8472-dbce263d4ca7 --variable RP_LAUNCH:"Demo Tests" --variable RP_PROJECT:fileflipper --loglevel DEBUG tests\home_page_validations.robot`

There were 3 tests which ran and passed, but the console throws this error:
`Calling method 'end_suite' of listener 'reportportal_listener' failed: ResponseError: 40023: Finish launch is not allowed. Launch '5ace08933cdea20001f57335' has items '[5ace08933cdea20001f57337]' with 'IN_PROGRESS' status`

**Comment by amalsgit** [comment]
Hi @ailjushkin , I have an update on the issue. This issue does not happen when tests are executed using tags. For example:
`python -m robot -d results -i Smoke -e Head --listener reportportal_listener --escape quot:Q --variable RP_ENDPOINT:http://192.168.99.100:8080 --variable RP_UUID:531345ef-2c3a-4b28-8472-dbce263d4ca7 --variable RP_LAUNCH:"Demo Tests" --variable RP_PROJECT:fileflipper --loglevel DEBUG tests`

Here I am using the test tag `-i Smoke` to execute the tests. In this case, reportportal works just fine.
When I remove the tag and execute the tests by specifying the test file directly the error is reproduced.

**Comment by ailjushkin** [comment]
> There were 3 tests which ran and passed, but the console throws this error:

This error is not the root cause. You can find the root cause only if you debug your test in integration with Report Portal.

Please, collect more information.

At lease, set loglevel as TRACE: --loglevel TRACE

And attach here:

* Debug file: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#debug-file
* Sys log: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#system-log
* output.xml

At most, that would be great if you give me a line number in the listener, where the key error occurs. Before that moment, I won't help you.

**Comment by samratashok87** [comment]
I will check with the latest build.

**Comment by samratashok87** [comment]
Hi , 

I tried in the latest build, 
Below is the testcase I am running 
Hello World
    [Tags]    chrome    headless
    Log To Console   Hello World
When I try running the testcase integrating with RP. I am seeing the following in the debug file. 

==============================================================================
20180417 14:19:06.757 - INFO - + START SUITE: Headless [ ]
==============================================================================
20180417 14:19:06.834 - INFO - +- START TEST: Hello World [ ]
------------------------------------------------------------------------------
20180417 14:19:06.858 - INFO - +-- START KW: BuiltIn.Log To Console [ Hello World ]
20180417 14:19:06.946 - INFO - +-- END KW: BuiltIn.Log To Console (68)
------------------------------------------------------------------------------
20180417 14:19:06.968 - INFO - +- END TEST: Hello World (113)
------------------------------------------------------------------------------
20180417 14:19:07.001 - INFO - + END SUITE: Headless (508)
===================================================================

At the end of the run the listener fails with the following error , 
[ ERROR ] Calling method 'end_suite' of listener 'reportportal_listener' failed: ResponseError: 40023: Finish launch is not allowed. Launch '5ad5b50dbfe52300017cb480' has items '[5ad5b50dbfe52300017cb482]' with 'IN_PROGRESS' status

I am not able to find the line number in the listener where this error occurs. The RP launch continues to run I am force finishing the launch to stop it.

**Comment by samratashok87** [comment]
[error_log.txt](https://github.com/ailjushkin/robotframework-reportportal-ng/files/1918898/error_log.txt)

**Comment by samratashok87** [comment]
I have reopened the issue with the logs.

**Comment by ailjushkin** [comment]
I will update Readme with steps to debug this problem and write you back.

**Comment by keyjm** [comment]
Any update on this issue? I am seeing exact same issue with my tests.

**Comment by amalsgit** [comment]
Hi @ailjushkin Please find the syslogs, debug log and output.xml for the issue. Please let me know if this information is helpful.
I am trying to debug further using pdb libraries and see if I can find the root cause.
[debug.txt](https://github.com/ailjushkin/robotframework-reportportal-ng/files/2061199/debug.txt)
[syslog.txt](https://github.com/ailjushkin/robotframework-reportportal-ng/files/2061201/syslog.txt)

[output.zip](https://github.com/ailjushkin/robotframework-reportportal-ng/files/2061205/output.zip)

**Comment by amalsgit** [comment]
Hi @ailjushkin Please find the syslog, debug log and the output.xml file for the issue. This is the error logged in the syslogs for this issue.

`20180601 11:34:43.389 | ERROR | Calling method 'end_suite' of listener 'reportportal_listener' failed: OperationCompletionError: No 'msg' in response: {"error_code":40023,"message":"Finish launch is not allowed. Launch '5b10e182b9d821000114c47d' has items '[5b10e182b9d821000114c47f]' with 'IN_PROGRESS' status"}
20180601 11:34:43.389 | INFO  | Details:
Traceback (most recent call last):
  File "C:\Users\ajayara\AppData\Local\Programs\Python\Python36-32\lib\site-packages\reportportal_listener\__init__.py", line 138, in end_suite
    self.robot_service.finish_launch(launch=suite)
  File "C:\Users\ajayara\AppData\Local\Programs\Python\Python36-32\lib\site-packages\reportportal_listener\service.py", line 138, in finish_launch
    RobotService.rp.finish_launch(**fl_rq)
  File "C:\Users\ajayara\AppData\Local\Programs\Python\Python36-32\lib\site-packages\reportportal_client\service.py", line 146, in finish_launch
    status=status)
  File "C:\Users\ajayara\AppData\Local\Programs\Python\Python36-32\lib\site-packages\reportportal_client\service.py", line 142, in _finalize_launch
    return _get_msg(r)
  File "C:\Users\ajayara\AppData\Local\Programs\Python\Python36-32\lib\site-packages\reportportal_client\service.py", line 25, in _get_msg
    "No 'msg' in response: {0}".format(response.text))`

Please let me know if this information helps. I am also trying to debug using pdb library and find out the root cause.
[logs.zip](https://github.com/ailjushkin/robotframework-reportportal-ng/files/2061218/logs.zip)

**Comment by ailjushkin** [comment]
That's another bug, please create for the ""No 'msg' in response" another issue.

This is not connected to this issue.

**Comment by amalsgit** [comment]
@ailjushkin Sorry for that. I was trying to debug the issue and commented out some code which raises the exception in the _get_data method. That's why the error looks different.
This is the original error:
`20180601 12:16:32.607 | ERROR | Calling method 'end_suite' of listener 'reportportal_listener' failed: ResponseError: 40023: Finish launch is not allowed. Launch '5b10eb4db9d821000114c755' has items '[5b10eb4db9d821000114c757]' with 'IN_PROGRESS' status
20180601 12:16:32.607 | INFO  | Details:
Traceback (most recent call last):
  File "C:\Users\ajayara\AppData\Local\Programs\Python\Python36-32\lib\site-packages\reportportal_listener\__init__.py", line 138, in end_suite
    self.robot_service.finish_launch(launch=suite)
  File "C:\Users\ajayara\AppData\Local\Programs\Python\Python36-32\lib\site-packages\reportportal_listener\service.py", line 138, in finish_launch
    RobotService.rp.finish_launch(**fl_rq)
  File "C:\Users\ajayara\AppData\Local\Programs\Python\Python36-32\lib\site-packages\reportportal_client\service.py", line 145, in finish_launch
    status=status)
  File "C:\Users\ajayara\AppData\Local\Programs\Python\Python36-32\lib\site-packages\reportportal_client\service.py", line 141, in _finalize_launch
    return _get_msg(r)
  File "C:\Users\ajayara\AppData\Local\Programs\Python\Python36-32\lib\site-packages\reportportal_client\service.py", line 22, in _get_msg
    return _get_data(response)["msg"]
  File "C:\Users\ajayara\AppData\Local\Programs\Python\Python36-32\lib\site-packages\reportportal_client\service.py", line 34, in _get_data
    raise ResponseError(error_messages[0])`

logs: 
[logs.zip](https://github.com/ailjushkin/robotframework-reportportal-ng/files/2061385/logs.zip)

**Comment by amalsgit** [comment]
@ailjushkin I have more updates on this issue.
Looks like this issue is occurring only when I provide the complete test file path while running the test like:
 `python -m robot -b debug.txt -d results -i Debug --listener reportportal_listener --escape quot:Q --variable RP_ENDPOINT:http://myreportportal.com --variable RP_UUID:myuuid --variable RP_LAUNCH:"Smoke Tests" --variable RP_PROJECT:superadmin_personal --loglevel TRACE **tests/design_package/home_page.robot**`

Report portal error is not coming when the same test case is run using tags and by not providing the robot test file name like this:
 `python -m robot -b debug.txt -d results -i Debug --listener reportportal_listener --escape quot:Q --variable RP_ENDPOINT:http://myreportportal.com --variable RP_UUID:myuuid --variable RP_LAUNCH:"Smoke Tests" --variable RP_PROJECT:superadmin_personal --loglevel TRACE **tests**`

[passed_log.zip](https://github.com/ailjushkin/robotframework-reportportal-ng/files/2062243/passed_log.zip)

**Comment by flyaroundme** [comment]
Hi, all,

Please check it with the new version.

**Comment by ailjushkin** [comment]
@flyaroundme @amalsgit 
Hi, thank you very much indeed for your pull-request, thanks for the help.
Please, retest with the new version 1.0.4.9: 

`pip install -U robotframework_reportportal_ng`
